version: '3'

services: 
    web:
        container_name: APP_TASKFY
        build: '.'
        ports: 
            - '4000:4000'
        depends_on: 
            - db
        links:
            - db
    db:
        image: 'mongo'
        container_name: MONGO_TASKFY
        ports: 
            - '27017:27017'
        volumes:
            - ./data/db:/data/db
